development:
  adapter: sqlite3
  database: ":memory:"

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_app_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
